name: Build and Publish

on:
  push:
    branches:  ['main']
    tags: ['v*']
  pull_request:

env:
  PACKAGE_NAME: segment-inspector-${{ github.ref_name }}
  WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
  WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
  CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - uses: pnpm/action-setup@v2
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Project
        run: pnpm run build
      - name: Create Packages
        run: ${{ startsWith(github.ref, 'refs/tags/') && 'pnpm run pack --sign' || 'pnpm run pack' }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: packages/*
  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: packages
      - name: Display Workspace Files
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: packages/*
