name: Build and Publish

on:
  push:
    branches:  ['main']
    tags: ['v*']
  pull_request:

env:
  PACKAGE_NAME: segment-inspector-${{ github.ref_name }}
  WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
  WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
  CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - uses: pnpm/action-setup@v2
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Project
        run: pnpm run build
      - name: Create Packages
        run: ${{ startsWith(github.ref, 'refs/tags/') && 'pnpm run pack --sign' || 'pnpm run pack' }}
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: packages/*
      - name: Generate Release Notes
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpm run changelog -r 2 -o RELEASE_NOTES.md
      - name: Upload Release Notes
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: notes
          path: RELEASE_NOTES.md
  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Packages
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: packages
      - name: Download Release Notes
        uses: actions/download-artifact@v2
        with:
          name: notes
          path: notes
      - name: Display Workspace Files
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: notes/RELEASE_NOTES.md
          files: packages/*
